name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PEM }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - name: Set up environment variables
      run: |
        ssh -i ~/.ssh/ec2.pem ec2-user@${{ secrets.EC2_ADDRESS }} "bash -s" << 'EOF'
        if [ ! -f ~/var/www/onboard-be/.env ]; then
          touch ~/var/www/onboard-be/.env
        fi
        echo "${{ secrets.ENV_FILE }}" > ~/var/www/onboard-be/.env
        EOF
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2.pem -T ec2-user@${{ secrets.EC2_ADDRESS }} << 'EOF'
          cd ~/var/www/onboard-be
          git fetch origin main
          git reset --hard origin/main
          docker stop onboard-be || true
          docker rm onboard-be || true

          docker build -t onboard-be .
          docker run -d --name onboard-be \
            -p 3000:3000 \
            --env-file .env \
            --restart always \
            onboard-backend

          docker image prune -f
          EOF
